applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/demosph/goit-devops-hw.git
      path: lesson-8-9/charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app
    namespace: argocd
    url: https://github.com/demosph/goit-devops-hw.git
    username: demosph
    password: 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

repoConfig:
  insecure: "true"
  enableLfs: "true"