replicaCount: 2  # використовується, якщо autoscaling.enabled = false

image:
  repository: 265766434317.dkr.ecr.us-east-2.amazonaws.com/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer   # зовнішній доступ
  port: 8000

ingress:
  enabled: false

# Змінні середовища для Deployment
workingDir: "/app/goit"

# Змінні середовища для ConfigMap
config:
  POSTGRES_HOST: ${rds_endpoint} # output з rds модуля terraform
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

# Змінні середовища для HPA за CPU: мають бути requests
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70