applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: ${github_repo_url}
      path: ${django_app_dir}
      targetRevision: ${github_branch}
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app
    namespace: argocd
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
