{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .url }}
  username: {{ .username }}
  password: {{ .password }}
  {{- if $.Values.repoConfig.insecure }}
  insecure: "{{ $.Values.repoConfig.insecure }}"
  {{- end }}
  {{- if $.Values.repoConfig.enableLfs }}
  enableLfs: "{{ $.Values.repoConfig.enableLfs }}"
  {{- end }}
---
{{- end }}